// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiffRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileId           string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	LocalMerkleRoot  []byte                 `protobuf:"bytes,2,opt,name=local_merkle_root,json=localMerkleRoot,proto3" json:"local_merkle_root,omitempty"`    // 32-byte Merkle root
	KnownChunkHashes [][]byte               `protobuf:"bytes,3,rep,name=known_chunk_hashes,json=knownChunkHashes,proto3" json:"known_chunk_hashes,omitempty"` // Chunks the requester already has
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *DiffRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DiffRequest) GetLocalMerkleRoot() []byte {
	if x != nil {
		return x.LocalMerkleRoot
	}
	return nil
}

func (x *DiffRequest) GetKnownChunkHashes() [][]byte {
	if x != nil {
		return x.KnownChunkHashes
	}
	return nil
}

type DiffResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FileId             string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	RemoteMerkleRoot   []byte                 `protobuf:"bytes,2,opt,name=remote_merkle_root,json=remoteMerkleRoot,proto3" json:"remote_merkle_root,omitempty"`
	IsSynced           bool                   `protobuf:"varint,3,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	MissingChunkHashes [][]byte               `protobuf:"bytes,4,rep,name=missing_chunk_hashes,json=missingChunkHashes,proto3" json:"missing_chunk_hashes,omitempty"` // Chunks the requester needs to fetch
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *DiffResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DiffResponse) GetRemoteMerkleRoot() []byte {
	if x != nil {
		return x.RemoteMerkleRoot
	}
	return nil
}

func (x *DiffResponse) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

func (x *DiffResponse) GetMissingChunkHashes() [][]byte {
	if x != nil {
		return x.MissingChunkHashes
	}
	return nil
}

type AvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHashes   [][]byte               `protobuf:"bytes,1,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *AvailabilityRequest) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type AvailabilityResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AvailableChunkHashes [][]byte               `protobuf:"bytes,1,rep,name=available_chunk_hashes,json=availableChunkHashes,proto3" json:"available_chunk_hashes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AvailabilityResponse) Reset() {
	*x = AvailabilityResponse{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResponse) ProtoMessage() {}

func (x *AvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResponse.ProtoReflect.Descriptor instead.
func (*AvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *AvailabilityResponse) GetAvailableChunkHashes() [][]byte {
	if x != nil {
		return x.AvailableChunkHashes
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PingResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FileCount          uint32                 `protobuf:"varint,2,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	ChunkCount         uint32                 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	UptimeSecs         uint64                 `protobuf:"varint,4,opt,name=uptime_secs,json=uptimeSecs,proto3" json:"uptime_secs,omitempty"`
	ActiveStreams      int64                  `protobuf:"varint,5,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	MaxStreams         int64                  `protobuf:"varint,6,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	DegradedWatchPaths uint32                 `protobuf:"varint,7,opt,name=degraded_watch_paths,json=degradedWatchPaths,proto3" json:"degraded_watch_paths,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetFileCount() uint32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *PingResponse) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *PingResponse) GetUptimeSecs() uint64 {
	if x != nil {
		return x.UptimeSecs
	}
	return 0
}

func (x *PingResponse) GetActiveStreams() int64 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *PingResponse) GetMaxStreams() int64 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *PingResponse) GetDegradedWatchPaths() uint32 {
	if x != nil {
		return x.DegradedWatchPaths
	}
	return 0
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\acontrol\"\x80\x01\n" +
	"\vDiffRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12*\n" +
	"\x11local_merkle_root\x18\x02 \x01(\fR\x0flocalMerkleRoot\x12,\n" +
	"\x12known_chunk_hashes\x18\x03 \x03(\fR\x10knownChunkHashes\"\xa4\x01\n" +
	"\fDiffResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12,\n" +
	"\x12remote_merkle_root\x18\x02 \x01(\fR\x10remoteMerkleRoot\x12\x1b\n" +
	"\tis_synced\x18\x03 \x01(\bR\bisSynced\x120\n" +
	"\x14missing_chunk_hashes\x18\x04 \x03(\fR\x12missingChunkHashes\"8\n" +
	"\x13AvailabilityRequest\x12!\n" +
	"\fchunk_hashes\x18\x01 \x03(\fR\vchunkHashes\"L\n" +
	"\x14AvailabilityResponse\x124\n" +
	"\x16available_chunk_hashes\x18\x01 \x03(\fR\x14availableChunkHashes\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x82\x02\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"file_count\x18\x02 \x01(\rR\tfileCount\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\rR\n" +
	"chunkCount\x12\x1f\n" +
	"\vuptime_secs\x18\x04 \x01(\x04R\n" +
	"uptimeSecs\x12%\n" +
	"\x0eactive_streams\x18\x05 \x01(\x03R\ractiveStreams\x12\x1f\n" +
	"\vmax_streams\x18\x06 \x01(\x03R\n" +
	"maxStreams\x120\n" +
	"\x14degraded_watch_paths\x18\a \x01(\rR\x12degradedWatchPaths2\xd9\x01\n" +
	"\x0eControlService\x12=\n" +
	"\x0eDiffMerkleTree\x12\x14.control.DiffRequest\x1a\x15.control.DiffResponse\x12S\n" +
	"\x14GetChunkAvailability\x12\x1c.control.AvailabilityRequest\x1a\x1d.control.AvailabilityResponse\x123\n" +
	"\x04Ping\x12\x14.control.PingRequest\x1a\x15.control.PingResponseB7Z5github.com/MitNarodia/Nutanix-hackathon/proto/controlb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_control_proto_goTypes = []any{
	(*DiffRequest)(nil),          // 0: control.DiffRequest
	(*DiffResponse)(nil),         // 1: control.DiffResponse
	(*AvailabilityRequest)(nil),  // 2: control.AvailabilityRequest
	(*AvailabilityResponse)(nil), // 3: control.AvailabilityResponse
	(*PingRequest)(nil),          // 4: control.PingRequest
	(*PingResponse)(nil),         // 5: control.PingResponse
}
var file_proto_control_proto_depIdxs = []int32{
	0, // 0: control.ControlService.DiffMerkleTree:input_type -> control.DiffRequest
	2, // 1: control.ControlService.GetChunkAvailability:input_type -> control.AvailabilityRequest
	4, // 2: control.ControlService.Ping:input_type -> control.PingRequest
	1, // 3: control.ControlService.DiffMerkleTree:output_type -> control.DiffResponse
	3, // 4: control.ControlService.GetChunkAvailability:output_type -> control.AvailabilityResponse
	5, // 5: control.ControlService.Ping:output_type -> control.PingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
